var lambdaFunction = require('../index');
var context = {};
jest.setTimeout(100000);

function callback(error, data) {
    console.log(JSON.stringify(data, null, 2));
}

describe('index', () => {
    it('mall/order/generateOrder', async () => {
        let event = {
            "requestType": "mall/order/generateOrder",
            "commonParam": {
                "userId": 525714,
                "platform": 2,
                "pkgGroup": 1,
                "deviceName": "ws_14e23baec7f82177",
                "costMoneyRatio": 2,
                "getMoneyRatio": 2,
                "purchaseCoinsRatio": 4,
                "clientIp": "182.139.182.73",
                "emailId": "121",
                "adjustAdid": "-",
                "adjustIdfa": "-",
                "adjustGpsAdid": "-"
            },
            "data": "H4sIAAAAAAAAAA3MvQrCMBRA4QtGiLgJLq66JjRVazM7+Q6C3Py1F9ukkBbx9XwyMx74ODtYw9bQMFDs7sl5Diz3aQJu0fb+RY4BwAE2E35HH+dH6f3zB6v8Xjgc85DmLMdCKXr5oRjLRgYjbaKYpdJaA1sWchxO2Nx0famV0JV1wtsWRYNBiSpczxpbbJyp/3AIYx6OAAAA",
            "sfsObjType": "RequestNewOrder",
            "sourceIP": "::ffff:127.0.0.1",
            "stage": "dev"
        };
        await lambdaFunction.handler(event, context, callback);
    });

    it('mall/order/listErrorOrder', async () => {
        let event = {
            "requestType": "mall/order/listErrorOrder",
            "commonParam": {
                "userId": 525714,
                "platform": 4,
                "pkgGroup": 1,
                "deviceName": "ws_e67d289897edcf0f9b1996449a27c62d8beb5",
                "costMoneyRatio": 2,
                "getMoneyRatio": 2,
                "purchaseCoinsRatio": 4,
                "clientIp": "182.139.182.73",
                "emailId": "121",
                "adjustAdid": "-",
                "adjustIdfa": "-",
                "adjustGpsAdid": "-"
            },
            "data": "H4sIAAAAAAAAABNiYGHgSE5MzkiNz0xhYWBgUGJgKS3NTOFgUDE2NTExN0lJ1E1OMTPXNTayTNJNTUlN1TU3MzK1ME8xMDRONGTgSy0qyi/yL0pJLfLJLC4RBJogUJqXnZdfnocsCADe3QYqZwAAAA==",
            "sfsObjType": "RequestErrorOrderList",
            "sourceIP": "::ffff:127.0.0.1",
            "stage": "dev"
        };
        await lambdaFunction.handler(event, context, callback);
    });

    it('mall/order/verifyOrder', async () => {
        let event = {
            "requestType": "mall/order/verifyOrder",
            "data": {
                "userId": 525714,
                "platform": 1,
                "orderNo": "21562852261525714",
                "packageName": "slots.machine.winning.ios",
                "receiptData": "MIIUCwYJKoZIhvcNAQcCoIIT/DCCE/gCAQExCzAJBgUrDgMCGgUAMIIDrAYJKoZIhvcNAQcBoIIDnQSCA5kxggOVMAoCARQCAQEEAgwAMAsCAQ4CAQEEAwIBajALAgEZAgEBBAMCAQMwDQIBCgIBAQQFFgMxMiswDQIBDQIBAQQFAgMB1SgwDgIBAQIBAQQGAgRPTpYaMA4CAQkCAQEEBgIEUDI1MjAOAgELAgEBBAYCBAcSYyAwDgIBEAIBAQQGAgQxhvlfMBACAQMCAQEECAwGMTU0MDIwMBACAQ8CAQEECAIGZBL/DUcNMBACARMCAQEECAwGMTUyMDEyMBQCAQACAQEEDAwKUHJvZHVjdGlvbjAYAgEEAgECBBCwpxuX0yiajL5L4pPR/iy6MBwCAQUCAQEEFDCUDdbf/COSRCkW6TR0xLWTQDnLMB4CAQgCAQEEFhYUMjAxOS0wNC0yNVQwOTo0OTo0N1owHgIBDAIBAQQWFhQyMDE5LTA0LTI1VDA5OjQ5OjQ3WjAeAgESAgEBBBYWFDIwMTktMDMtMjRUMTU6MTQ6MjdaMCMCAQICAQEEGwwZc2xvdHMubWFjaGluZS53aW5uaW5nLmlvczBGAgEHAgEBBD66OYbfgJirjnbCEIXcAykOd0e1pSLjjkFfruJTN6XRkYzqU3Z1gi7SeYI9LNsdiTuRaj1LOtOD53lXvbNkRDBLAgEGAgEBBENs2FbRJ7kIeSGHZwGcLlRGXgwCuAzBjq8NFQQ9tmEt+tqiAw35bEmEjPRzTt+/lcSrhw3Nwnd0ImDxag48WJMTa3cYMIIBbwIBEQIBAQSCAWUxggFhMAsCAgasAgEBBAIWADALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEBMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGrgIBAQQGAgRVNG/LMBoCAganAgEBBBEMDzcwMDAwMDM1MjgzOTY1NjAaAgIGqQIBAQQRDA83MDAwMDAzNTI4Mzk2NTYwHwICBqgCAQEEFhYUMjAxOS0wNC0yNVQwOTo0OTo0NlowHwICBqoCAQEEFhYUMjAxOS0wNC0yNVQwOTo0OTo0NlowNAICBqYCAQEEKwwpc2xvdHMubWFjaGluZS53aW5uaW5nLmlvcy5iaWd3aW53aGVlbC4wOTmggg5lMIIFfDCCBGSgAwIBAgIIDutXh+eeCY0wDQYJKoZIhvcNAQEFBQAwgZYxCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTUxMTEzMDIxNTA5WhcNMjMwMjA3MjE0ODQ3WjCBiTE3MDUGA1UEAwwuTWFjIEFwcCBTdG9yZSBhbmQgaVR1bmVzIFN0b3JlIFJlY2VpcHQgU2lnbmluZzEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApc+B/SWigVvWh+0j2jMcjuIjwKXEJss9xp/sSg1Vhv+kAteXyjlUbX1/slQYncQsUnGOZHuCzom6SdYI5bSIcc8/W0YuxsQduAOpWKIEPiF41du30I4SjYNMWypoN5PC8r0exNKhDEpYUqsS4+3dH5gVkDUtwswSyo1IgfdYeFRr6IwxNh9KBgxHVPM3kLiykol9X6SFSuHAnOC6pLuCl2P0K5PB/T5vysH1PKmPUhrAJQp2Dt7+mf7/wmv1W16sc1FJCFaJzEOQzI6BAtCgl7ZcsaFpaYeQEGgmJjm4HRBzsApdxXPQ33Y72C3ZiB7j7AfP4o7Q0/omVYHv4gNJIwIDAQABo4IB1zCCAdMwPwYIKwYBBQUHAQEEMzAxMC8GCCsGAQUFBzABhiNodHRwOi8vb2NzcC5hcHBsZS5jb20vb2NzcDAzLXd3ZHIwNDAdBgNVHQ4EFgQUkaSc/MR2t5+givRN9Y82Xe0rBIUwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBSIJxcJqbYYYIvs67r2R1nFUlSjtzCCAR4GA1UdIASCARUwggERMIIBDQYKKoZIhvdjZAUGATCB/jCBwwYIKwYBBQUHAgIwgbYMgbNSZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3JpdHkvMA4GA1UdDwEB/wQEAwIHgDAQBgoqhkiG92NkBgsBBAIFADANBgkqhkiG9w0BAQUFAAOCAQEADaYb0y4941srB25ClmzT6IxDMIJf4FzRjb69D70a/CWS24yFw4BZ3+Pi1y4FFKwN27a4/vw1LnzLrRdrjn8f5He5sWeVtBNephmGdvhaIJXnY4wPc/zo7cYfrpn4ZUhcoOAoOsAQNy25oAQ5H3O5yAX98t5/GioqbisB/KAgXNnrfSemM/j1mOC+RNuxTGf8bgpPyeIGqNKX86eOa1GiWoR1ZdEWBGLjwV/1CKnPaNmSAMnBjLP4jQBkulhgwHyvj3XKablbKtYdaG6YQvVMpzcZm8w7HHoZQ/Ojbb9IYAYMNpIr7N4YtRHaLSPQjvygaZwXG56AezlHRTBhL8cTqDCCBCIwggMKoAMCAQICCAHevMQ5baAQMA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTAeFw0xMzAyMDcyMTQ4NDdaFw0yMzAyMDcyMTQ4NDdaMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyjhUpstWqsgkOUjpjO7sX7h/JpG8NFN6znxjgGF3ZF6lByO2Of5QLRVWWHAtfsRuwUqFPi/w3oQaoVfJr3sY/2r6FRJJFQgZrKrbKjLtlmNoUhU9jIrsv2sYleADrAF9lwVnzg6FlTdq7Qm2rmfNUWSfxlzRvFduZzWAdjakh4FuOI/YKxVOeyXYWr9Og8GN0pPVGnG1YJydM05V+RJYDIa4Fg3B5XdFjVBIuist5JSF4ejEncZopbCj/Gd+cLoCWUt3QpE5ufXN4UzvwDtIjKblIV39amq7pxY1YNLmrfNGKcnow4vpecBqYWcVsvD95Wi8Yl9uz5nd7xtj/pJlqwIDAQABo4GmMIGjMB0GA1UdDgQWBBSIJxcJqbYYYIvs67r2R1nFUlSjtzAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm90dNfwheMC4GA1UdHwQnMCUwI6AhoB+GHWh0dHA6Ly9jcmwuYXBwbGUuY29tL3Jvb3QuY3JsMA4GA1UdDwEB/wQEAwIBhjAQBgoqhkiG92NkBgIBBAIFADANBgkqhkiG9w0BAQUFAAOCAQEAT8/vWb4s9bJsL4/uE4cy6AU1qG6LfclpDLnZF7x3LNRn4v2abTpZXN+DAb2yriphcrGvzcNFMI+jgw3OHUe08ZOKo3SbpMOYcoc7Pq9FC5JUuTK7kBhTawpOELbZHVBsIYAKiU5XjGtbPD2m/d73DSMdC0omhz+6kZJMpBkSGW1X9XpYh3toiuSGjErr4kkUqqXdVQCprrtLMK7hoLG8KYDmCXflvjSiAcp/3OIK5ju4u+y6YpXzBWNBgs0POx1MlaTbq/nJlelP5E3nJpmB6bz5tCnSAXpm4S6M9iGKxfh44YGuv9OQnamt86/9OBqWZzAcUaVc7HGKgrRsDwwVHzCCBLswggOjoAMCAQICAQIwDQYJKoZIhvcNAQEFBQAwYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMB4XDTA2MDQyNTIxNDAzNloXDTM1MDIwOTIxNDAzNlowYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5JGpCR+R2x5HUOsF7V55hC3rNqJXTFXsixmJ3vlLbPUHqyIwAugYPvhQCdN/QaiY+dHKZpwkaxHQo7vkGyrDH5WeegykR4tb1BY3M8vED03OFGnRyRly9V0O1X9fm/IlA7pVj01dDfFkNSMVSxVZHbOU9/acns9QusFYUGePCLQg98usLCBvcLY/ATCMt0PPD5098ytJKBrI/s61uQ7ZXhzWyz21Oq30Dw4AkguxIRYudNU8DdtiFqujcZJHU1XBry9Bs/j743DN5qNMRX4fTGtQlkGJxHRiCxCDQYczioGxMFjsWgQyjGizjx3eZXP/Z15lvEnYdp8zFGWhd5TJLQIDAQABo4IBejCCAXYwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCvQaUeUdgn+9GuNLkCm90dNfwheMB8GA1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm90dNfwheMIIBEQYDVR0gBIIBCDCCAQQwggEABgkqhkiG92NkBQEwgfIwKgYIKwYBBQUHAgEWHmh0dHBzOi8vd3d3LmFwcGxlLmNvbS9hcHBsZWNhLzCBwwYIKwYBBQUHAgIwgbYagbNSZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjANBgkqhkiG9w0BAQUFAAOCAQEAXDaZTC14t+2Mm9zzd5vydtJ3ME/BH4WDhRuZPUc38qmbQI4s1LGQEti+9HOb7tJkD8t5TzTYoj75eP9ryAfsfTmDi1Mg0zjEsb+aTwpr/yv8WacFCXwXQFYRHnTTt4sjO0ej1W8k4uvRt3DfD0XhJ8rxbXjt57UXF6jcfiI1yiXV2Q/Wa9SiJCMR96Gsj3OBYMYbWwkvkrL4REjwYDieFfU9JmcgijNq9w2Cz97roy/5U2pbZMBjM3f3OgcsVuvaDyEO2rpzGU+12TZ/wYdV2aeZuTJC+9jVcZ5+oVK3G72TQiQSKscPHbZNnF5jyEuAF1CqitXa5PzQCQc3sHV1ITGCAcswggHHAgEBMIGjMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5AggO61eH554JjTAJBgUrDgMCGgUAMA0GCSqGSIb3DQEBAQUABIIBAFjP+voN+0cFXAr+m46UkrqyRv3O26Cq4gKx5Rf8gYyfjq0Q+itIralhOXIIRDk5+7rz+nroKAl2zI1gbSpfHcwmnsuWpeadK7RK4s2MQ5pGeofKWv7tX8g/Q92slZBkuKVf5m2WJ/MWqSe2KptMG2CkZJ0melTk2PIOQ1CJaQYww79Foz4sXsDIY/sryAs1kwv0QyL1aYX1f/ya6Tz3mN8kFXkEH3mkxVIXAxsbTFRQFNjMv6fieJmUppWOlx9WLnpqH/XS6t+GQ5wePHRUd3/xksSUUjcB7MWBFDiXPAjOdLbvTwMdQMlWqJnS+CF5IY7TcLz/r0Rnpm5GnBwjq+8="
            }
        };
        await lambdaFunction.handler(event, context, callback);
    });

    it('mall/listGoods', async () => {
        let event = {
            "requestType": "mall/listGoods",
            "data": {"userId": 718, "billingCode": 'horn', "platform": 2}
        };
        await lambdaFunction.handler(event, context, callback);
    });

    it('mall/sendGoods', async () => {
        let event = {
            "requestType": "mall/sendGoods",
            "data": {"billingCode": 'horn', 'orderNo': '21557219285111'}
        };
        await lambdaFunction.handler(event, context, callback);
    });

    it('mall/order/updateOrderState', async () => {
        let event = {
            "requestType": "mall/order/updateOrderState",
            "commonParam": {
                "userId": 525714,
                "platform": 4,
                "pkgGroup": 1,
                "deviceName": "ws_e67d289897edcf0f9b1996449a27c62d8beb",
                "costMoneyRatio": 2,
                "getMoneyRatio": 2,
                "clientIp": "-",
                "emailId": "121",
                "adjustAdid": "-",
                "adjustIdfa": "-",
                "adjustGpsAdid": "-"
            },
            "data": {"msg": "complete", "orderNo": "", "state": 5},
            "sfsObjType": null,
            "sourceIP": "::ffff:127.0.0.1",
            "stage": "dev"
        };
        await lambdaFunction.handler(event, context, callback);
    });

    it('mall/getPurchaseResult', async () => {
        // let packageName = req.getStringParam('packageName');
        // let receiptData = req.getStringParam('receiptData');
        let event = {
            "requestType": "mall/getPurchaseResult",
            "commonParam": {"userId": 525714, "platform": 2, "pkgGroup": 1, "deviceName": "ws_14e23baec7f82177"},
            "data": {
                "packageName": 'slots.machine.winning.ios',
                "orderNo": '21562852261525714',
                "receiptData": 'MIIUCwYJKoZIhvcNAQcCoIIT/DCCE/gCAQExCzAJBgUrDgMCGgUAMIIDrAYJKoZIhvcNAQcBoIIDnQSCA5kxggOVMAoCARQCAQEEAgwAMAsCAQ4CAQEEAwIBajALAgEZAgEBBAMCAQMwDQIBCgIBAQQFFgMxMiswDQIBDQIBAQQFAgMB1SgwDgIBAQIBAQQGAgRPTpYaMA4CAQkCAQEEBgIEUDI1MjAOAgELAgEBBAYCBAcSYyAwDgIBEAIBAQQGAgQxhvlfMBACAQMCAQEECAwGMTU0MDIwMBACAQ8CAQEECAIGZBL/DUcNMBACARMCAQEECAwGMTUyMDEyMBQCAQACAQEEDAwKUHJvZHVjdGlvbjAYAgEEAgECBBCwpxuX0yiajL5L4pPR/iy6MBwCAQUCAQEEFDCUDdbf/COSRCkW6TR0xLWTQDnLMB4CAQgCAQEEFhYUMjAxOS0wNC0yNVQwOTo0OTo0N1owHgIBDAIBAQQWFhQyMDE5LTA0LTI1VDA5OjQ5OjQ3WjAeAgESAgEBBBYWFDIwMTktMDMtMjRUMTU6MTQ6MjdaMCMCAQICAQEEGwwZc2xvdHMubWFjaGluZS53aW5uaW5nLmlvczBGAgEHAgEBBD66OYbfgJirjnbCEIXcAykOd0e1pSLjjkFfruJTN6XRkYzqU3Z1gi7SeYI9LNsdiTuRaj1LOtOD53lXvbNkRDBLAgEGAgEBBENs2FbRJ7kIeSGHZwGcLlRGXgwCuAzBjq8NFQQ9tmEt+tqiAw35bEmEjPRzTt+/lcSrhw3Nwnd0ImDxag48WJMTa3cYMIIBbwIBEQIBAQSCAWUxggFhMAsCAgasAgEBBAIWADALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEBMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGrgIBAQQGAgRVNG/LMBoCAganAgEBBBEMDzcwMDAwMDM1MjgzOTY1NjAaAgIGqQIBAQQRDA83MDAwMDAzNTI4Mzk2NTYwHwICBqgCAQEEFhYUMjAxOS0wNC0yNVQwOTo0OTo0NlowHwICBqoCAQEEFhYUMjAxOS0wNC0yNVQwOTo0OTo0NlowNAICBqYCAQEEKwwpc2xvdHMubWFjaGluZS53aW5uaW5nLmlvcy5iaWd3aW53aGVlbC4wOTmggg5lMIIFfDCCBGSgAwIBAgIIDutXh+eeCY0wDQYJKoZIhvcNAQEFBQAwgZYxCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTUxMTEzMDIxNTA5WhcNMjMwMjA3MjE0ODQ3WjCBiTE3MDUGA1UEAwwuTWFjIEFwcCBTdG9yZSBhbmQgaVR1bmVzIFN0b3JlIFJlY2VpcHQgU2lnbmluZzEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApc+B/SWigVvWh+0j2jMcjuIjwKXEJss9xp/sSg1Vhv+kAteXyjlUbX1/slQYncQsUnGOZHuCzom6SdYI5bSIcc8/W0YuxsQduAOpWKIEPiF41du30I4SjYNMWypoN5PC8r0exNKhDEpYUqsS4+3dH5gVkDUtwswSyo1IgfdYeFRr6IwxNh9KBgxHVPM3kLiykol9X6SFSuHAnOC6pLuCl2P0K5PB/T5vysH1PKmPUhrAJQp2Dt7+mf7/wmv1W16sc1FJCFaJzEOQzI6BAtCgl7ZcsaFpaYeQEGgmJjm4HRBzsApdxXPQ33Y72C3ZiB7j7AfP4o7Q0/omVYHv4gNJIwIDAQABo4IB1zCCAdMwPwYIKwYBBQUHAQEEMzAxMC8GCCsGAQUFBzABhiNodHRwOi8vb2NzcC5hcHBsZS5jb20vb2NzcDAzLXd3ZHIwNDAdBgNVHQ4EFgQUkaSc/MR2t5+givRN9Y82Xe0rBIUwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBSIJxcJqbYYYIvs67r2R1nFUlSjtzCCAR4GA1UdIASCARUwggERMIIBDQYKKoZIhvdjZAUGATCB/jCBwwYIKwYBBQUHAgIwgbYMgbNSZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3JpdHkvMA4GA1UdDwEB/wQEAwIHgDAQBgoqhkiG92NkBgsBBAIFADANBgkqhkiG9w0BAQUFAAOCAQEADaYb0y4941srB25ClmzT6IxDMIJf4FzRjb69D70a/CWS24yFw4BZ3+Pi1y4FFKwN27a4/vw1LnzLrRdrjn8f5He5sWeVtBNephmGdvhaIJXnY4wPc/zo7cYfrpn4ZUhcoOAoOsAQNy25oAQ5H3O5yAX98t5/GioqbisB/KAgXNnrfSemM/j1mOC+RNuxTGf8bgpPyeIGqNKX86eOa1GiWoR1ZdEWBGLjwV/1CKnPaNmSAMnBjLP4jQBkulhgwHyvj3XKablbKtYdaG6YQvVMpzcZm8w7HHoZQ/Ojbb9IYAYMNpIr7N4YtRHaLSPQjvygaZwXG56AezlHRTBhL8cTqDCCBCIwggMKoAMCAQICCAHevMQ5baAQMA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTAeFw0xMzAyMDcyMTQ4NDdaFw0yMzAyMDcyMTQ4NDdaMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyjhUpstWqsgkOUjpjO7sX7h/JpG8NFN6znxjgGF3ZF6lByO2Of5QLRVWWHAtfsRuwUqFPi/w3oQaoVfJr3sY/2r6FRJJFQgZrKrbKjLtlmNoUhU9jIrsv2sYleADrAF9lwVnzg6FlTdq7Qm2rmfNUWSfxlzRvFduZzWAdjakh4FuOI/YKxVOeyXYWr9Og8GN0pPVGnG1YJydM05V+RJYDIa4Fg3B5XdFjVBIuist5JSF4ejEncZopbCj/Gd+cLoCWUt3QpE5ufXN4UzvwDtIjKblIV39amq7pxY1YNLmrfNGKcnow4vpecBqYWcVsvD95Wi8Yl9uz5nd7xtj/pJlqwIDAQABo4GmMIGjMB0GA1UdDgQWBBSIJxcJqbYYYIvs67r2R1nFUlSjtzAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm90dNfwheMC4GA1UdHwQnMCUwI6AhoB+GHWh0dHA6Ly9jcmwuYXBwbGUuY29tL3Jvb3QuY3JsMA4GA1UdDwEB/wQEAwIBhjAQBgoqhkiG92NkBgIBBAIFADANBgkqhkiG9w0BAQUFAAOCAQEAT8/vWb4s9bJsL4/uE4cy6AU1qG6LfclpDLnZF7x3LNRn4v2abTpZXN+DAb2yriphcrGvzcNFMI+jgw3OHUe08ZOKo3SbpMOYcoc7Pq9FC5JUuTK7kBhTawpOELbZHVBsIYAKiU5XjGtbPD2m/d73DSMdC0omhz+6kZJMpBkSGW1X9XpYh3toiuSGjErr4kkUqqXdVQCprrtLMK7hoLG8KYDmCXflvjSiAcp/3OIK5ju4u+y6YpXzBWNBgs0POx1MlaTbq/nJlelP5E3nJpmB6bz5tCnSAXpm4S6M9iGKxfh44YGuv9OQnamt86/9OBqWZzAcUaVc7HGKgrRsDwwVHzCCBLswggOjoAMCAQICAQIwDQYJKoZIhvcNAQEFBQAwYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMB4XDTA2MDQyNTIxNDAzNloXDTM1MDIwOTIxNDAzNlowYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5JGpCR+R2x5HUOsF7V55hC3rNqJXTFXsixmJ3vlLbPUHqyIwAugYPvhQCdN/QaiY+dHKZpwkaxHQo7vkGyrDH5WeegykR4tb1BY3M8vED03OFGnRyRly9V0O1X9fm/IlA7pVj01dDfFkNSMVSxVZHbOU9/acns9QusFYUGePCLQg98usLCBvcLY/ATCMt0PPD5098ytJKBrI/s61uQ7ZXhzWyz21Oq30Dw4AkguxIRYudNU8DdtiFqujcZJHU1XBry9Bs/j743DN5qNMRX4fTGtQlkGJxHRiCxCDQYczioGxMFjsWgQyjGizjx3eZXP/Z15lvEnYdp8zFGWhd5TJLQIDAQABo4IBejCCAXYwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCvQaUeUdgn+9GuNLkCm90dNfwheMB8GA1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm90dNfwheMIIBEQYDVR0gBIIBCDCCAQQwggEABgkqhkiG92NkBQEwgfIwKgYIKwYBBQUHAgEWHmh0dHBzOi8vd3d3LmFwcGxlLmNvbS9hcHBsZWNhLzCBwwYIKwYBBQUHAgIwgbYagbNSZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjANBgkqhkiG9w0BAQUFAAOCAQEAXDaZTC14t+2Mm9zzd5vydtJ3ME/BH4WDhRuZPUc38qmbQI4s1LGQEti+9HOb7tJkD8t5TzTYoj75eP9ryAfsfTmDi1Mg0zjEsb+aTwpr/yv8WacFCXwXQFYRHnTTt4sjO0ej1W8k4uvRt3DfD0XhJ8rxbXjt57UXF6jcfiI1yiXV2Q/Wa9SiJCMR96Gsj3OBYMYbWwkvkrL4REjwYDieFfU9JmcgijNq9w2Cz97roy/5U2pbZMBjM3f3OgcsVuvaDyEO2rpzGU+12TZ/wYdV2aeZuTJC+9jVcZ5+oVK3G72TQiQSKscPHbZNnF5jyEuAF1CqitXa5PzQCQc3sHV1ITGCAcswggHHAgEBMIGjMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5AggO61eH554JjTAJBgUrDgMCGgUAMA0GCSqGSIb3DQEBAQUABIIBAFjP+voN+0cFXAr+m46UkrqyRv3O26Cq4gKx5Rf8gYyfjq0Q+itIralhOXIIRDk5+7rz+nroKAl2zI1gbSpfHcwmnsuWpeadK7RK4s2MQ5pGeofKWv7tX8g/Q92slZBkuKVf5m2WJ/MWqSe2KptMG2CkZJ0melTk2PIOQ1CJaQYww79Foz4sXsDIY/sryAs1kwv0QyL1aYX1f/ya6Tz3mN8kFXkEH3mkxVIXAxsbTFRQFNjMv6fieJmUppWOlx9WLnpqH/XS6t+GQ5wePHRUd3/xksSUUjcB7MWBFDiXPAjOdLbvTwMdQMlWqJnS+CF5IY7TcLz/r0Rnpm5GnBwjq+8='
            }
        };
        await lambdaFunction.handler(event, context, callback);
    });

    it('mall/getGoodsList', async () => {
        // let packageName = req.getStringParam('packageName');
        // let receiptData = req.getStringParam('receiptData');
        let event = {
            "requestType": "mall/getGoodsList",
            "commonParam": {"userId": 525714, "platform": 2, "pkgGroup": 1, "deviceName": "ws_14e23baec7f82177"},
            "data": {
                "packageName": 'slots.machine.winning.ios',
                "orderNo": '41559022366525714',
                "pageCode": "shop",
                "receiptData": 'MIIUCwYJKoZIhvcNAQcCoIIT/DCCE/gCAQExCzAJBgUrDgMCGgUAMIIDrAYJKoZIhvcNAQcBoIIDnQSCA5kxggOVMAoCARQCAQEEAgwAMAsCAQ4CAQEEAwIBajALAgEZAgEBBAMCAQMwDQIBCgIBAQQFFgMxMiswDQIBDQIBAQQFAgMB1SgwDgIBAQIBAQQGAgRPTpYaMA4CAQkCAQEEBgIEUDI1MjAOAgELAgEBBAYCBAcSYyAwDgIBEAIBAQQGAgQxhvlfMBACAQMCAQEECAwGMTU0MDIwMBACAQ8CAQEECAIGZBL/DUcNMBACARMCAQEECAwGMTUyMDEyMBQCAQACAQEEDAwKUHJvZHVjdGlvbjAYAgEEAgECBBCwpxuX0yiajL5L4pPR/iy6MBwCAQUCAQEEFDCUDdbf/COSRCkW6TR0xLWTQDnLMB4CAQgCAQEEFhYUMjAxOS0wNC0yNVQwOTo0OTo0N1owHgIBDAIBAQQWFhQyMDE5LTA0LTI1VDA5OjQ5OjQ3WjAeAgESAgEBBBYWFDIwMTktMDMtMjRUMTU6MTQ6MjdaMCMCAQICAQEEGwwZc2xvdHMubWFjaGluZS53aW5uaW5nLmlvczBGAgEHAgEBBD66OYbfgJirjnbCEIXcAykOd0e1pSLjjkFfruJTN6XRkYzqU3Z1gi7SeYI9LNsdiTuRaj1LOtOD53lXvbNkRDBLAgEGAgEBBENs2FbRJ7kIeSGHZwGcLlRGXgwCuAzBjq8NFQQ9tmEt+tqiAw35bEmEjPRzTt+/lcSrhw3Nwnd0ImDxag48WJMTa3cYMIIBbwIBEQIBAQSCAWUxggFhMAsCAgasAgEBBAIWADALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEBMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGrgIBAQQGAgRVNG/LMBoCAganAgEBBBEMDzcwMDAwMDM1MjgzOTY1NjAaAgIGqQIBAQQRDA83MDAwMDAzNTI4Mzk2NTYwHwICBqgCAQEEFhYUMjAxOS0wNC0yNVQwOTo0OTo0NlowHwICBqoCAQEEFhYUMjAxOS0wNC0yNVQwOTo0OTo0NlowNAICBqYCAQEEKwwpc2xvdHMubWFjaGluZS53aW5uaW5nLmlvcy5iaWd3aW53aGVlbC4wOTmggg5lMIIFfDCCBGSgAwIBAgIIDutXh+eeCY0wDQYJKoZIhvcNAQEFBQAwgZYxCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTUxMTEzMDIxNTA5WhcNMjMwMjA3MjE0ODQ3WjCBiTE3MDUGA1UEAwwuTWFjIEFwcCBTdG9yZSBhbmQgaVR1bmVzIFN0b3JlIFJlY2VpcHQgU2lnbmluZzEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApc+B/SWigVvWh+0j2jMcjuIjwKXEJss9xp/sSg1Vhv+kAteXyjlUbX1/slQYncQsUnGOZHuCzom6SdYI5bSIcc8/W0YuxsQduAOpWKIEPiF41du30I4SjYNMWypoN5PC8r0exNKhDEpYUqsS4+3dH5gVkDUtwswSyo1IgfdYeFRr6IwxNh9KBgxHVPM3kLiykol9X6SFSuHAnOC6pLuCl2P0K5PB/T5vysH1PKmPUhrAJQp2Dt7+mf7/wmv1W16sc1FJCFaJzEOQzI6BAtCgl7ZcsaFpaYeQEGgmJjm4HRBzsApdxXPQ33Y72C3ZiB7j7AfP4o7Q0/omVYHv4gNJIwIDAQABo4IB1zCCAdMwPwYIKwYBBQUHAQEEMzAxMC8GCCsGAQUFBzABhiNodHRwOi8vb2NzcC5hcHBsZS5jb20vb2NzcDAzLXd3ZHIwNDAdBgNVHQ4EFgQUkaSc/MR2t5+givRN9Y82Xe0rBIUwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBSIJxcJqbYYYIvs67r2R1nFUlSjtzCCAR4GA1UdIASCARUwggERMIIBDQYKKoZIhvdjZAUGATCB/jCBwwYIKwYBBQUHAgIwgbYMgbNSZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3JpdHkvMA4GA1UdDwEB/wQEAwIHgDAQBgoqhkiG92NkBgsBBAIFADANBgkqhkiG9w0BAQUFAAOCAQEADaYb0y4941srB25ClmzT6IxDMIJf4FzRjb69D70a/CWS24yFw4BZ3+Pi1y4FFKwN27a4/vw1LnzLrRdrjn8f5He5sWeVtBNephmGdvhaIJXnY4wPc/zo7cYfrpn4ZUhcoOAoOsAQNy25oAQ5H3O5yAX98t5/GioqbisB/KAgXNnrfSemM/j1mOC+RNuxTGf8bgpPyeIGqNKX86eOa1GiWoR1ZdEWBGLjwV/1CKnPaNmSAMnBjLP4jQBkulhgwHyvj3XKablbKtYdaG6YQvVMpzcZm8w7HHoZQ/Ojbb9IYAYMNpIr7N4YtRHaLSPQjvygaZwXG56AezlHRTBhL8cTqDCCBCIwggMKoAMCAQICCAHevMQ5baAQMA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTAeFw0xMzAyMDcyMTQ4NDdaFw0yMzAyMDcyMTQ4NDdaMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyjhUpstWqsgkOUjpjO7sX7h/JpG8NFN6znxjgGF3ZF6lByO2Of5QLRVWWHAtfsRuwUqFPi/w3oQaoVfJr3sY/2r6FRJJFQgZrKrbKjLtlmNoUhU9jIrsv2sYleADrAF9lwVnzg6FlTdq7Qm2rmfNUWSfxlzRvFduZzWAdjakh4FuOI/YKxVOeyXYWr9Og8GN0pPVGnG1YJydM05V+RJYDIa4Fg3B5XdFjVBIuist5JSF4ejEncZopbCj/Gd+cLoCWUt3QpE5ufXN4UzvwDtIjKblIV39amq7pxY1YNLmrfNGKcnow4vpecBqYWcVsvD95Wi8Yl9uz5nd7xtj/pJlqwIDAQABo4GmMIGjMB0GA1UdDgQWBBSIJxcJqbYYYIvs67r2R1nFUlSjtzAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm90dNfwheMC4GA1UdHwQnMCUwI6AhoB+GHWh0dHA6Ly9jcmwuYXBwbGUuY29tL3Jvb3QuY3JsMA4GA1UdDwEB/wQEAwIBhjAQBgoqhkiG92NkBgIBBAIFADANBgkqhkiG9w0BAQUFAAOCAQEAT8/vWb4s9bJsL4/uE4cy6AU1qG6LfclpDLnZF7x3LNRn4v2abTpZXN+DAb2yriphcrGvzcNFMI+jgw3OHUe08ZOKo3SbpMOYcoc7Pq9FC5JUuTK7kBhTawpOELbZHVBsIYAKiU5XjGtbPD2m/d73DSMdC0omhz+6kZJMpBkSGW1X9XpYh3toiuSGjErr4kkUqqXdVQCprrtLMK7hoLG8KYDmCXflvjSiAcp/3OIK5ju4u+y6YpXzBWNBgs0POx1MlaTbq/nJlelP5E3nJpmB6bz5tCnSAXpm4S6M9iGKxfh44YGuv9OQnamt86/9OBqWZzAcUaVc7HGKgrRsDwwVHzCCBLswggOjoAMCAQICAQIwDQYJKoZIhvcNAQEFBQAwYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMB4XDTA2MDQyNTIxNDAzNloXDTM1MDIwOTIxNDAzNlowYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5JGpCR+R2x5HUOsF7V55hC3rNqJXTFXsixmJ3vlLbPUHqyIwAugYPvhQCdN/QaiY+dHKZpwkaxHQo7vkGyrDH5WeegykR4tb1BY3M8vED03OFGnRyRly9V0O1X9fm/IlA7pVj01dDfFkNSMVSxVZHbOU9/acns9QusFYUGePCLQg98usLCBvcLY/ATCMt0PPD5098ytJKBrI/s61uQ7ZXhzWyz21Oq30Dw4AkguxIRYudNU8DdtiFqujcZJHU1XBry9Bs/j743DN5qNMRX4fTGtQlkGJxHRiCxCDQYczioGxMFjsWgQyjGizjx3eZXP/Z15lvEnYdp8zFGWhd5TJLQIDAQABo4IBejCCAXYwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCvQaUeUdgn+9GuNLkCm90dNfwheMB8GA1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm90dNfwheMIIBEQYDVR0gBIIBCDCCAQQwggEABgkqhkiG92NkBQEwgfIwKgYIKwYBBQUHAgEWHmh0dHBzOi8vd3d3LmFwcGxlLmNvbS9hcHBsZWNhLzCBwwYIKwYBBQUHAgIwgbYagbNSZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjANBgkqhkiG9w0BAQUFAAOCAQEAXDaZTC14t+2Mm9zzd5vydtJ3ME/BH4WDhRuZPUc38qmbQI4s1LGQEti+9HOb7tJkD8t5TzTYoj75eP9ryAfsfTmDi1Mg0zjEsb+aTwpr/yv8WacFCXwXQFYRHnTTt4sjO0ej1W8k4uvRt3DfD0XhJ8rxbXjt57UXF6jcfiI1yiXV2Q/Wa9SiJCMR96Gsj3OBYMYbWwkvkrL4REjwYDieFfU9JmcgijNq9w2Cz97roy/5U2pbZMBjM3f3OgcsVuvaDyEO2rpzGU+12TZ/wYdV2aeZuTJC+9jVcZ5+oVK3G72TQiQSKscPHbZNnF5jyEuAF1CqitXa5PzQCQc3sHV1ITGCAcswggHHAgEBMIGjMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5AggO61eH554JjTAJBgUrDgMCGgUAMA0GCSqGSIb3DQEBAQUABIIBAFjP+voN+0cFXAr+m46UkrqyRv3O26Cq4gKx5Rf8gYyfjq0Q+itIralhOXIIRDk5+7rz+nroKAl2zI1gbSpfHcwmnsuWpeadK7RK4s2MQ5pGeofKWv7tX8g/Q92slZBkuKVf5m2WJ/MWqSe2KptMG2CkZJ0melTk2PIOQ1CJaQYww79Foz4sXsDIY/sryAs1kwv0QyL1aYX1f/ya6Tz3mN8kFXkEH3mkxVIXAxsbTFRQFNjMv6fieJmUppWOlx9WLnpqH/XS6t+GQ5wePHRUd3/xksSUUjcB7MWBFDiXPAjOdLbvTwMdQMlWqJnS+CF5IY7TcLz/r0Rnpm5GnBwjq+8='
            }
        };
        await lambdaFunction.handler(event, context, callback);
    });

    it('testAndroidVerification', async () => {
        global.__env__ = require('../config/Config');
        global.commons = require('@private/lambda-commons');
        let AndroidVerification = require('../src/verification/AndroidVerification');
        let verifier = new AndroidVerification(2);

        let ret = await verifier.verifyReceipt({
            sku: 'clubillion.social.slots.casino.friends.free.android.coins.299',
            purchaseData: JSON.stringify({
                packageName:"clubillion.social.slots.casino.friends.free.android",
                productId: "clubillion.social.slots.casino.friends.free.android.coins.299",
                purchaseToken: "nobolgmpjocnbomompfmkaam.AO-J1OxBIGsZcxFEyogCFWr28oOcNBeZmXPFnv2wStjr0vf0sy_Vu0WMuFT1jiGakc64ZcH-ZShrGN_zcYLKbKQ69J_fZUSBEvY3DNe2w_g9BCEoAXTQJvYfupaMwP9iLJXoc0NZ7k8DeHi4gcPzWv29s8dBxDY2O7Q5tnFrQ7fWDrNIrGHWWDSJnFTz0L_J0Sua3bgjjfO8e2JrHgETUTGxwhv0DsdxRuWwk5Cju6wB12rTYvMsnmQ"
            })
        });

        console.log(ret);
    });
});